/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as uniswapContractsMoonbeam from "./uniswap-contracts-moonbeam";
export type { uniswapContractsMoonbeam };
